name: Feedback your Fluentd use-case/testimonial
description: Feedback your Fluentd use-case/testimonial, How do you use Fluentd in your service?
labels: "use-case"
body:
  - type: markdown
    attributes:
      value: |
        We want to collect Fluentd's use-case.
        If you use Fluentd implicitly in your services and simply not published yet,
        Please consider to feedback us! Your use-case helps to spread Fluentd!
        See current testimonials in https://www.fluentd.org/testimonials.
  - type: textarea
    id: caption
    attributes:
      label: What is your service or company name which use Fluentd?
      description: Descripbe your service name or company name. See https://www.fluentd.org/testimonials in details.
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: What is your service or company logo? (optional)
      description: Descripbe URI to your service or company logo which is accessible publicly.
    validations:
      required: false
  - type: textarea
    id: testimonial
    attributes:
      label: What is your service or company and How do you use Fluentd in your service or company?
      description: Write the actual use-case about Fluentd.
    validations:
      required: true
  - type: textarea
    id: addtional-context
    attributes:
      label: Additional context
      description: Add any other context about your use-case/testimonial.
    validations:
      required: false
